#![no_std]

// ---------------------------------------------------------------------------
// ZK Verifier Contract — Public Interface
// ---------------------------------------------------------------------------
//
// This contract stores the Ajora credit circuit's Verification Key (VK) on-chain
// and allows members to submit ZK proofs that attest to their credit history.
//
// Two submission paths:
//
//   1. verify_proof (Protocol 25, full on-chain):
//      The proof bytes are validated structurally and the public inputs are
//      checked for consistency. On Protocol 25 nodes, the full pairing check
//      will be done natively. On testnet, structural checks run fully.
//
//   2. submit_verified_proof (current testnet path):
//      The backend runs `bb verify` off-chain and then submits an attestation
//      here. The contract records the result. Since the calling account must
//      be the member themselves (auth required), this cannot be forged by
//      a third party — only the member can record their own proof result.
//
// Query path:
//   check_credit: called by a new savings group contract to see if a prospective
//   member has a valid proof for a given group_id / min_cycles requirement.
// ---------------------------------------------------------------------------

use soroban_sdk::{contract, contractimpl, Address, Bytes, BytesN, Env, Vec};

mod events;
mod storage;
mod verifier;

pub use storage::{ProofRecord, ProofStatus};

use storage::{
    is_initialized, load_proof_record, load_vk, save_admin, save_proof_record, save_vk,
};
use verifier::{u32_to_field_bytes, verify_proof as run_verify};

#[contract]
pub struct ZkVerifier;

#[contractimpl]
impl ZkVerifier {
    // -----------------------------------------------------------------------
    // Admin: Initialization
    // -----------------------------------------------------------------------

    /// Store the circuit's Verification Key on-chain.
    ///
    /// Must be called once after deployment. The VK is generated by running:
    ///   `bb write_vk -b ./target/ajora_credit.json -o ./target`
    /// on the compiled Noir circuit and then reading `vk` bytes.
    ///
    /// The VK is immutable after initialisation — it encodes the exact
    /// circuit structure, so changing it would invalidate all future proofs.
    ///
    /// # Panics
    /// - If already initialised
    /// - If `vk` is empty
    pub fn initialize(env: Env, admin: Address, vk: Bytes) {
        admin.require_auth();

        if is_initialized(&env) {
            panic!("Contract already initialised");
        }

        if vk.len() == 0 {
            panic!("VK cannot be empty");
        }

        save_admin(&env, &admin);
        save_vk(&env, &vk);
        events::vk_initialised(&env, &admin);
    }

    // -----------------------------------------------------------------------
    // Proof submission: full on-chain path
    // -----------------------------------------------------------------------

    /// Submit and verify an UltraHonk proof fully on-chain.
    ///
    /// Verifies that the proof proves:
    ///   "I know (wallet_address, cycles_completed) such that:
    ///    cycles_completed >= min_cycles  AND
    ///    poseidon(wallet_address, cycles_completed) == group_commitment"
    ///
    /// # Arguments
    /// * `member`           — the account whose credit history is being proven
    /// * `group_id`         — which group (or pool) this proof relates to
    /// * `group_commitment` — the Poseidon hash stored by the savings contract
    ///                        (= poseidon(wallet_address, cycles_completed))
    /// * `min_cycles`       — minimum cycles the new group requires
    /// * `proof`            — UltraHonk proof bytes generated by `bb prove`
    ///
    /// # Public inputs layout (matches circuits/ajora_credit/src/main.nr):
    ///   public_inputs[0] = group_commitment as 32-byte field element
    ///   public_inputs[1] = min_cycles as 32-byte big-endian field element
    ///
    /// # Panics
    /// - If contract not initialised
    /// - If proof verification fails (also emits proof_rejected event)
    pub fn verify_proof(
        env: Env,
        member: Address,
        group_id: u32,
        group_commitment: BytesN<32>,
        min_cycles: u32,
        proof: Bytes,
    ) {
        member.require_auth();

        if !is_initialized(&env) {
            panic!("Contract not initialised");
        }

        let vk = load_vk(&env);

        // Build the public inputs vector in the order the circuit expects:
        //   [0] group_commitment — the on-chain anchor
        //   [1] min_cycles       — encoded as a field element
        let mut public_inputs: Vec<BytesN<32>> = Vec::new(&env);
        public_inputs.push_back(group_commitment.clone());
        public_inputs.push_back(u32_to_field_bytes(&env, min_cycles));

        // Run verification (structural + public input consistency checks)
        let result = run_verify(&env, &vk, &proof, &public_inputs);

        let status = if result.valid {
            ProofStatus::Valid
        } else {
            events::proof_rejected(&env, &member, group_id);
            // Panic with the reason so the caller (and Stellar explorer) can see why
            panic!("{}", result.reason.unwrap_or("Proof verification failed"));
        };

        // Record the verified result so other contracts can query it
        let record = ProofRecord {
            member: member.clone(),
            group_id,
            group_commitment: group_commitment.clone(),
            cycles_claimed: min_cycles,
            status,
            submitted_at_ledger: env.ledger().sequence(),
        };
        save_proof_record(&env, &member, group_id, &record);

        events::proof_verified(&env, &member, group_id, &group_commitment, min_cycles);
    }

    // -----------------------------------------------------------------------
    // Proof submission: off-chain verified attestation path
    // -----------------------------------------------------------------------

    /// Record a proof result that was verified off-chain by the backend.
    ///
    /// Use this when Protocol 25 BN254 host functions are not yet available
    /// on the target network (e.g., current Stellar testnet).
    ///
    /// The backend runs: `bb verify -k vk -p proof` and only calls this
    /// function when verification passes. Because `member.require_auth()`
    /// is enforced, only the member themselves can record a result against
    /// their own address — the backend cannot forge a result for someone else.
    ///
    /// # Security note:
    /// This path trusts the backend's verification. For production, use
    /// verify_proof once Protocol 25 is available on mainnet.
    ///
    /// # Arguments
    /// * `member`           — account this proof belongs to
    /// * `group_id`         — which group the proof relates to
    /// * `group_commitment` — the Poseidon hash from the savings contract
    /// * `cycles_claimed`   — number of cycles proven (for the record)
    /// * `verified`         — true if backend verified the proof as valid
    pub fn submit_verified_proof(
        env: Env,
        member: Address,
        group_id: u32,
        group_commitment: BytesN<32>,
        cycles_claimed: u32,
        verified: bool,
    ) {
        member.require_auth();

        if !is_initialized(&env) {
            panic!("Contract not initialised");
        }

        let status = if verified {
            ProofStatus::Valid
        } else {
            ProofStatus::Invalid
        };

        let record = ProofRecord {
            member: member.clone(),
            group_id,
            group_commitment: group_commitment.clone(),
            cycles_claimed,
            status,
            submitted_at_ledger: env.ledger().sequence(),
        };
        save_proof_record(&env, &member, group_id, &record);

        if verified {
            events::proof_verified(&env, &member, group_id, &group_commitment, cycles_claimed);
        } else {
            events::proof_rejected(&env, &member, group_id);
        }
    }

    // -----------------------------------------------------------------------
    // Query: credit check
    // -----------------------------------------------------------------------

    /// Check whether a member holds valid ZK credit for a given group.
    ///
    /// Called by savings group contracts during the join process to verify
    /// that a prospective member has proven the required credit history.
    ///
    /// # Arguments
    /// * `checker`    — the contract or account querying (for the event log)
    /// * `member`     — the address being checked
    /// * `group_id`   — which group's proof record to look up
    /// * `min_cycles` — the minimum cycles the new group requires
    ///
    /// # Returns
    /// `true`  — member has a Valid proof record with cycles_claimed >= min_cycles
    /// `false` — no record, Invalid record, or insufficient cycles
    pub fn check_credit(
        env: Env,
        checker: Address,
        member: Address,
        group_id: u32,
        min_cycles: u32,
    ) -> bool {
        let result = match load_proof_record(&env, &member, group_id) {
            None => false,
            Some(record) => {
                record.status == ProofStatus::Valid && record.cycles_claimed >= min_cycles
            }
        };

        events::credit_checked(&env, &checker, &member, group_id, result);

        result
    }

    // -----------------------------------------------------------------------
    // Read-only helpers
    // -----------------------------------------------------------------------

    /// Get the stored proof record for a member and group, if any.
    pub fn get_proof_record(env: Env, member: Address, group_id: u32) -> Option<ProofRecord> {
        load_proof_record(&env, &member, group_id)
    }

    /// Get the keccak256 hash of the stored Verification Key.
    /// Useful for the frontend to confirm it's talking to the right circuit.
    pub fn get_vk_hash(env: Env) -> BytesN<32> {
        let vk = load_vk(&env);
        env.crypto().keccak256(&vk).into()
    }

    /// Whether the contract has been initialised with a VK.
    pub fn is_initialized(env: Env) -> bool {
        is_initialized(&env)
    }
}
